<?php

namespace Rosh\PaymentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentOrderRepository extends EntityRepository
{
}
