services:
    main.news.admin.news:
        class: Application\Project\MainBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Новости", label: "Новости" }
        arguments:
            - ~
            - Application\Project\MainBundle\Entity\News
            - SonataAdminBundle:CRUD
    main.news.admin.newsLink:
        class: Application\Project\MainBundle\Admin\NewsLinkAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        arguments:
            - ~
            - Application\Project\MainBundle\Entity\NewsLink
            - SonataAdminBundle:CRUD
    main.news.admin.newsCategory:
        class: Application\Project\MainBundle\Admin\NewsCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Новости", label: "Категории новостей" }
        arguments:
            - ~
            - Application\Project\MainBundle\Entity\NewsCategory
            - SonataAdminBundle:CRUD
    main.pages.admin:
        class: Application\Project\MainBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Страницы", label: "Страницы" }
        arguments:
            - ~
            - Application\Project\MainBundle\Entity\Page
            - SonataAdminBundle:CRUD
    main.slider.admin:
        class: Application\Project\MainBundle\Admin\SliderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Слайдер", label: "Слайдер" }
        arguments:
            - ~
            - Application\Project\MainBundle\Entity\Slider
            - SonataAdminBundle:CRUD
    main.content.admin:
        class: Application\Project\MainBundle\Admin\ContentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Сервисы", label: "Контент" }
        arguments:
            - ~
            - Application\Project\MainBundle\Entity\Content
            - SonataAdminBundle:CRUD
    main.news.admin.newsCategory:
        class: Application\Project\MainBundle\Admin\ContentCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Сервисы", label: "Категории контента" }
        arguments:
            - ~
            - Application\Project\MainBundle\Entity\ContentCategory
            - SonataAdminBundle:CRUD
    main.service.admin:
        class: Application\Project\MainBundle\Admin\ServiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Сервисы", label: "Сервисы" }
        arguments:
            - ~
            - Application\Project\MainBundle\Entity\Service
            - SonataAdminBundle:CRUD
            - SonataAdminBundle:CRUD
    main.operator.admin:
        class: Application\Project\MainBundle\Admin\OperatorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Операторы", label: "Операторы" }
        arguments:
            - ~
            - Application\Project\MainBundle\Entity\Operator
            - SonataAdminBundle:CRUD
    main.operatorCode.admin:
        class: Application\Project\MainBundle\Admin\OperatorCodeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Операторы", label: "Коды операторов" }
        arguments:
            - ~
            - Application\Project\MainBundle\Entity\OperatorCode
            - SonataAdminBundle:CRUD
    main.code.admin:
        class: Application\Project\MainBundle\Admin\CodeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Операторы", label: "Коды пополнения" }
        arguments:
            - ~
            - Application\Project\MainBundle\Entity\Code
            - SonataAdminBundle:CRUD
