homepage:
    pattern:  /
    defaults: { _controller: MainBundle:Main:index }

category_show:
    pattern:  /category/{url}
    defaults: { _controller: MainBundle:Page:category }

page_show:
    pattern:  /page/{url}
    defaults: { _controller: MainBundle:Page:show }

product_show:
    pattern:  /product/{id}
    defaults: { _controller: MainBundle:Page:product }

order_new:
    pattern:  /order/new/{id_product}
    defaults: { _controller: MainBundle:Order:new }