processor:
    pattern:  /processor/{paymentService}
    defaults: { _controller: PaymentBundle:Base:processor }
    methods:  [POST, GET]

successful:
    pattern:  /successful/{paymentService}
    defaults: { _controller: PaymentBundle:Base:success }
    methods:  [GET]

fail:
    pattern:  /fail/{paymentService}
    defaults: { _controller: PaymentBundle:Base:fail }
    methods:  [GET]
