processor:
    pattern:  /{paymentService}
    defaults: { _controller: PaymentBundle:Base:processor }
    methods:  [POST, GET]

successful:
    pattern:  /{paymentService}
    defaults: { _controller: PaymentBundle:Base:success }
    methods:  [GET]

fail:
    pattern:  /{paymentService}
    defaults: { _controller: PaymentBundle:Base:fail }
    methods:  [GET]
